version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs"
  ]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true